#!/usr/bin/env node

/**
 * Deployment Script for Bantah On-Chain Challenges
 * Deploys all three contracts to Base Testnet Sepolia
 * 
 * Usage: npx ts-node deploy.ts
 * 
 * Requires environment variables:
 * - ADMIN_PRIVATE_KEY: Private key of admin account
 * - BASESCAN_API_KEY: Optional, for verification
 */

import ethers from "ethers";
import * as fs from "fs";
import * as path from "path";

// Read contract ABIs
const readABI = (contractName: string): string => {
  const abiPath = path.join(__dirname, "artifacts", `${contractName}.json`);
  if (!fs.existsSync(abiPath)) {
    console.error(`⚠️  Contract ${contractName}.json not found. Have you compiled contracts?`);
    console.error(`Run: npx hardhat compile`);
    process.exit(1);
  }
  const artifact = JSON.parse(fs.readFileSync(abiPath, "utf-8"));
  return artifact.abi;
};

// Read compiled bytecode
const readBytecode = (contractName: string): string => {
  const artifactPath = path.join(__dirname, "artifacts", `${contractName}.json`);
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  return artifact.bytecode;
};

async function deploy() {
  const adminPrivateKey = process.env.ADMIN_PRIVATE_KEY;
  if (!adminPrivateKey) {
    console.error("❌ ADMIN_PRIVATE_KEY not set in environment");
    process.exit(1);
  }

  // Setup provider and signer
  const provider = new ethers.JsonRpcProvider("https://sepolia.base.org");
  const wallet = new ethers.Wallet(adminPrivateKey, provider);

  console.log("\n🚀 Deploying Bantah On-Chain Challenge System");
  console.log(`📍 Network: Base Testnet Sepolia (Chain ID: 84532)`);
  console.log(`👤 Deployer: ${wallet.address}`);

  // Check balance
  const balance = await provider.getBalance(wallet.address);
  console.log(`💰 Balance: ${ethers.formatEther(balance)} ETH\n`);

  if (balance === 0n) {
    console.error("❌ No balance on deployer account. Get testnet ETH from faucet:");
    console.error("   https://www.alchemy.com/faucets/base-sepolia");
    process.exit(1);
  }

  try {
    // Step 1: Deploy BantahPoints
    console.log("📋 Step 1/4: Deploying BantahPoints.sol...");
    const pointsBytecode = readBytecode("BantahPoints");
    const pointsABI = readABI("BantahPoints");
    
    const pointsFactory = new ethers.ContractFactory(pointsABI, pointsBytecode, wallet);
    const pointsContract = await pointsFactory.deploy();
    await pointsContract.waitForDeployment();
    const pointsAddress = await pointsContract.getAddress();
    console.log(`✅ BantahPoints deployed: ${pointsAddress}\n`);

    // Step 2: Deploy ChallengeFactory
    console.log("📋 Step 2/4: Deploying ChallengeFactory.sol...");
    const factoryBytecode = readBytecode("ChallengeFactory");
    const factoryABI = readABI("ChallengeFactory");
    
    const factoryFactory = new ethers.ContractFactory(factoryABI, factoryBytecode, wallet);
    const challengeFactory = await factoryFactory.deploy(pointsAddress, wallet.address);
    await challengeFactory.waitForDeployment();
    const factoryAddress = await challengeFactory.getAddress();
    console.log(`✅ ChallengeFactory deployed: ${factoryAddress}\n`);

    // Step 3: Deploy PointsEscrow
    console.log("📋 Step 3/4: Deploying PointsEscrow.sol...");
    const escrowBytecode = readBytecode("PointsEscrow");
    const escrowABI = readABI("PointsEscrow");
    
    const escrowFactory = new ethers.ContractFactory(escrowABI, escrowBytecode, wallet);
    const pointsEscrow = await escrowFactory.deploy(pointsAddress, factoryAddress);
    await pointsEscrow.waitForDeployment();
    const escrowAddress = await pointsEscrow.getAddress();
    console.log(`✅ PointsEscrow deployed: ${escrowAddress}\n`);

    // Step 4: Setup permissions
    console.log("📋 Step 4/4: Setting up permissions...");
    
    const pointsContractInstance = new ethers.Contract(pointsAddress, pointsABI, wallet);
    const setManagerTx = await pointsContractInstance.setPointsManager(factoryAddress);
    await setManagerTx.wait();
    console.log(`✅ Set ChallengeFactory as PointsManager\n`);

    // Output results
    const envContent = `
# Bantah On-Chain Challenge System - Base Testnet Sepolia
# Generated by deploy.ts

VITE_BASE_TESTNET_RPC=https://sepolia.base.org
VITE_CHAIN_ID=84532

# Smart Contracts
VITE_POINTS_CONTRACT_ADDRESS=${pointsAddress}
VITE_CHALLENGE_FACTORY_ADDRESS=${factoryAddress}
VITE_POINTS_ESCROW_ADDRESS=${escrowAddress}

# Tokens
VITE_USDC_ADDRESS=0x833589fCD6eDb6E08f4c7C32D4f71b3566dA8860
VITE_USDT_ADDRESS=0x3c499c542cEF5E3811e1192ce70d8cC7d307B653

# Admin (for signing challenge resolutions)
ADMIN_PRIVATE_KEY=${adminPrivateKey}
ADMIN_ADDRESS=${wallet.address}

# Paymaster (for gas sponsorship)
VITE_PAYMASTER_ADDRESS=<ADD_PAYMASTER_ADDRESS>
VITE_ENTRY_POINT_ADDRESS=0x5FF137D4b0FDCD49DcA30c7B618636e2d6cf7c1e
`;

    fs.writeFileSync(".env.base-sepolia", envContent);
    console.log("✅ Deployment Complete!\n");
    console.log("📄 Contract Addresses:");
    console.log(`   BantahPoints: ${pointsAddress}`);
    console.log(`   ChallengeFactory: ${factoryAddress}`);
    console.log(`   PointsEscrow: ${escrowAddress}\n`);
    console.log("📝 Environment variables saved to .env.base-sepolia");
    console.log("💡 Next steps:");
    console.log("   1. Copy variables from .env.base-sepolia to .env");
    console.log("   2. Get Paymaster address from Alchemy/Pimlico");
    console.log("   3. Start Phase 2: Backend blockchain client setup\n");

  } catch (error) {
    console.error("❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  }
}

deploy().catch(console.error);
